dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  kovan:
    verify: True
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'